spring:
  application:
    name: euraka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/