eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: ds-gateway
zuul:
  routes:
    api-a:
      path: /usergateway/**
      serviceId: ds-user

